name: my_kopilka
description: Виртуальный трекер физической копилки (Flutter).
publish_to: "none"
version: 2.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path_provider: ^2.1.4
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true